name = "baan studio theme 2020"
license = "MIT"
licenselink = "https://github.com/mozo-works/baanstudio-theme/blob/master/LICENSE"
description = "A boostrap v4 based theme for baanstudio."
homepage = "https://github.com/mozo-works/baanstudio-theme"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "yeongtaek, Hong"
  homepage = "https://mozo.kr"
